// Generated by gencpp from file realtime/Delayed.msg
// DO NOT EDIT!


#ifndef REALTIME_MESSAGE_DELAYED_H
#define REALTIME_MESSAGE_DELAYED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realtime
{
template <class ContainerAllocator>
struct Delayed_
{
  typedef Delayed_<ContainerAllocator> Type;

  Delayed_()
    : delayed(false)  {
    }
  Delayed_(const ContainerAllocator& _alloc)
    : delayed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _delayed_type;
  _delayed_type delayed;





  typedef boost::shared_ptr< ::realtime::Delayed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realtime::Delayed_<ContainerAllocator> const> ConstPtr;

}; // struct Delayed_

typedef ::realtime::Delayed_<std::allocator<void> > Delayed;

typedef boost::shared_ptr< ::realtime::Delayed > DelayedPtr;
typedef boost::shared_ptr< ::realtime::Delayed const> DelayedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realtime::Delayed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realtime::Delayed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realtime

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'realtime': ['/home/riley/catkin_ws/src/realtime/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realtime::Delayed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realtime::Delayed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realtime::Delayed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realtime::Delayed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realtime::Delayed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realtime::Delayed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realtime::Delayed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9f55addc8a4b231e9f74c9f4032e734";
  }

  static const char* value(const ::realtime::Delayed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9f55addc8a4b231ULL;
  static const uint64_t static_value2 = 0xe9f74c9f4032e734ULL;
};

template<class ContainerAllocator>
struct DataType< ::realtime::Delayed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realtime/Delayed";
  }

  static const char* value(const ::realtime::Delayed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realtime::Delayed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool delayed\n"
;
  }

  static const char* value(const ::realtime::Delayed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realtime::Delayed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.delayed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Delayed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realtime::Delayed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realtime::Delayed_<ContainerAllocator>& v)
  {
    s << indent << "delayed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.delayed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALTIME_MESSAGE_DELAYED_H
