// Generated by gencpp from file realtime/Message.msg
// DO NOT EDIT!


#ifndef REALTIME_MESSAGE_MESSAGE_H
#define REALTIME_MESSAGE_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realtime
{
template <class ContainerAllocator>
struct Message_
{
  typedef Message_<ContainerAllocator> Type;

  Message_()
    : info()  {
    }
  Message_(const ContainerAllocator& _alloc)
    : info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::realtime::Message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realtime::Message_<ContainerAllocator> const> ConstPtr;

}; // struct Message_

typedef ::realtime::Message_<std::allocator<void> > Message;

typedef boost::shared_ptr< ::realtime::Message > MessagePtr;
typedef boost::shared_ptr< ::realtime::Message const> MessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realtime::Message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realtime::Message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realtime

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'realtime': ['/home/riley/catkin_ws/src/realtime/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realtime::Message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realtime::Message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realtime::Message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realtime::Message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realtime::Message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realtime::Message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realtime::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c10fc26d5cca9a4b9114f5fc5dea9570";
  }

  static const char* value(const ::realtime::Message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc10fc26d5cca9a4bULL;
  static const uint64_t static_value2 = 0x9114f5fc5dea9570ULL;
};

template<class ContainerAllocator>
struct DataType< ::realtime::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realtime/Message";
  }

  static const char* value(const ::realtime::Message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realtime::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string info\n"
;
  }

  static const char* value(const ::realtime::Message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realtime::Message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realtime::Message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realtime::Message_<ContainerAllocator>& v)
  {
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALTIME_MESSAGE_MESSAGE_H
